awestruct:
  build: ./ruby
  ports:
    - "4242"
  links:
    - drupal
    - searchisko
  privileged: true
  volumes:
    - ../:/home/awestruct/developer.redhat.com
  environment:
    - google_api_key
    - dcp_user
    - dcp_password
    - vimeo_client_secret
    - vimeo_access_token_secret
    - vimeo_access_token
    - cache_password
    - cache_url
    - cache_user
    - github_token
    - drupal_user
    - drupal_password
drupal:
  build: ./drupal
  ports:
    - "80"
  links:
    - drupalmysql
  volumes:
    - ../_drupal/themes/:/var/www/html/sites/all/themes
    - ../_drupal/scripts/:/drupal/bin
  environment:
    - DB_NAME=drupal
    - DB_USER=drupal
    - DB_PASSWORD=drupal
  privileged: true
drupalmysql:
  build: ./mysql
  environment:
    - DB_NAME=drupal
    - DB_USER=drupal
    - DB_PASSWORD=drupal
  ports:
    - "3306"
mysql:
  build: ./mysql
  environment:
    - DB_NAME=searchisko
    - DB_USER=searchisko
    - DB_PASSWORD=searchisko
  ports:
    - "3306"
elasticsearch:
  build: ./elasticsearch
  ports:
   - "9200"
   - "9300"
searchisko:
  build: ./searchisko
  ports:
   - "8080"
  environment:
    - DB_NAME=searchisko
    - DB_USER=searchisko
    - DB_PASSWORD=searchisko
  links:
   - mysql
   - elasticsearch
searchiskoconfigure:
  build: ./searchisko_configure
  links:
   - mysql
   - elasticsearch
   - searchisko
